In [1]:
import pandas as pd

In [2]:
student_assessment_db = pd.read_csv('cleaned_data/clean_studentAssessment.csv')
assessments_db = pd.read_csv('cleaned_data/clean_assessments.csv')

In [3]:
assessment_scores_db = pd.merge(student_assessment_db,assessments_db, how='left', on='id_assessment')
assessment_scores_db = assessment_scores_db[
    [
        'code_module',
        'code_presentation',
        'id_student',
        'id_assessment',
        'assessment_type',
        'score'
    ]
]

In [4]:
assessment_scores_db.sort_values(by=['id_student', 'id_assessment'], inplace=True)

In [5]:
assessment_scores_db.head()

,code_module,code_presentation,id_student,id_assessment,assessment_type,score
1756,AAA,2014J,6516,1758,TMA,60.0
1970,AAA,2014J,6516,1759,TMA,48.0
2376,AAA,2014J,6516,1760,TMA,63.0
2685,AAA,2014J,6516,1761,TMA,61.0
2871,AAA,2014J,6516,1762,TMA,77.0

In [6]:
assessment_scores_db.info()

<class 'pandas.DataFrame'>
Index: 173912 entries, 1756 to 45940
Data columns (total 6 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   code_module        173912 non-null  str
 1   code_presentation  173912 non-null  str
 2   id_student         173912 non-null  int64
 3   id_assessment      173912 non-null  int64
 4   assessment_type    173912 non-null  str
 5   score              173739 non-null  float64
dtypes: float64(1), int64(2), str(3)
memory usage: 9.3 MB

In [7]:
assessment_pivot_db = assessment_scores_db.pivot_table(index='id_student', columns='assessment_type', values='score', aggfunc='mean')

In [8]:
assessment_pivot_db = assessment_pivot_db[['CMA', 'TMA', 'Exam']]

In [9]:
assessment_pivot_db.reset_index(inplace=True)

In [10]:
assessment_pivot_db.columns.name = None

In [11]:
assessment_pivot_db.head()

   id_student    CMA   TMA  Exam
0        6516    NaN  61.8   NaN
1        8462    NaN  87.0   NaN
2       11391    NaN  82.0   NaN
3       23629  100.0  65.0   NaN
4       23698   75.0  72.5  80.0

In [12]:
assessment_pivot_db[['CMA', 'TMA', 'Exam']].describe()

                CMA           TMA         Exam
count  14400.000000  22669.000000  4633.000000
mean      79.493005     71.284393    65.117958
std       16.781101     15.347883    20.470561
min        0.000000      0.000000     0.000000
25%       72.000000     62.500000    50.000000
50%       83.000000     73.250000    66.000000
75%       91.714286     82.400000    82.000000
max      100.000000    100.000000   100.000000

In [13]:
student_info_db = pd.read_csv('cleaned_data/clean_studentInfo.csv')
student_vle_db = pd.read_csv('cleaned_data/clean_studentVle.csv')

In [14]:
student_details_db = pd.merge(student_info_db, student_vle_db, how='left', on=['id_student', 'code_presentation', 'code_module'])
student_details_db = pd.merge(student_details_db, assessment_pivot_db, how='left', on='id_student')

In [16]:
student_details_db = student_details_db[
    [
        'id_student',
        'code_module',
        'code_presentation',
        'gender',
        'highest_education',
        'region',
        'imd_band',
        'age_band',
        'disability',
        'num_of_prev_attempts',
        'studied_credits',
        'site_count',
        'CMA',
        'TMA',
        'Exam',
        'final_result'
    ]
]

In [17]:
student_details_db.info()

<class 'pandas.DataFrame'>
RangeIndex: 32593 entries, 0 to 32592
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_student            32593 non-null  int64
 1   code_module           32593 non-null  str
 2   code_presentation     32593 non-null  str
 3   gender                32593 non-null  str
 4   highest_education     32593 non-null  str
 5   region                32593 non-null  str
 6   imd_band              32593 non-null  str
 7   age_band              32593 non-null  str
 8   disability            32593 non-null  bool
 9   num_of_prev_attempts  32593 non-null  int64
 10  studied_credits       32593 non-null  int64
 11  site_count            29228 non-null  float64
 12  CMA                   16944 non-null  float64
 13  TMA                   25960 non-null  float64
 14  Exam                  5998 non-null   float64
 15  final_result          32593 non-null  str
dtypes: bool(1), float64(4), int64(3), str(8)
memory usage: 3.8 MB

In [18]:
student_details_db.head(10)

,id_student,code_module,code_presentation,gender,highest_education,region,imd_band,age_band,disability,num_of_prev_attempts,studied_credits,site_count,CMA,TMA,Exam,final_result
0,11391,AAA,2013J,M,HE Qualification,East Anglian Region,90-100%,55<=,False,0,240,196.0,NaN,82.0,NaN,Pass
1,28400,AAA,2013J,F,HE Qualification,Scotland,20-30%,35-55,False,0,60,430.0,NaN,66.4,NaN,Pass
2,30268,AAA,2013J,F,A Level or Equivalent,North Western Region,30-40%,35-55,True,0,60,76.0,NaN,NaN,NaN,Withdrawn
3,31604,AAA,2013J,F,A Level or Equivalent,South East Region,50-60%,35-55,False,0,60,663.0,NaN,76.0,NaN,Pass
4,32885,AAA,2013J,F,Lower Than A Level,West Midlands Region,50-60%,0-35,False,0,60,352.0,NaN,54.4,NaN,Pass
5,38053,AAA,2013J,M,A Level or Equivalent,Wales,80-90%,35-55,False,0,60,723.0,NaN,68.0,NaN,Pass
6,45462,AAA,2013J,M,HE Qualification,Scotland,30-40%,0-35,False,0,60,355.0,NaN,68.0,NaN,Pass
7,45642,AAA,2013J,F,A Level or Equivalent,North Western Region,90-100%,0-35,False,0,120,531.0,NaN,72.4,NaN,Pass
8,52130,AAA,2013J,F,A Level or Equivalent,East Anglian Region,70-80%,0-35,False,0,90,593.0,NaN,71.4,NaN,Pass
9,53025,AAA,2013J,M,Post Graduate Qualification,North Region,Unknown,55<=,False,0,60,904.0,NaN,78.0,NaN,Pass

In [19]:
print(student_details_db.duplicated(subset=['id_student', 'code_module', 'code_presentation']).sum())

0

In [20]:
student_model_data_db = student_details_db
student_model_data_db.to_csv('model_data/student_data_db.csv', index=False)