In [1]:
import pandas as pd

In [ ]:
student_info = pd.read_csv('raw_data/studentInfo.csv')

In [20]:
student_info.head()

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,False,Pass
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,False,Pass
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,True,Withdrawn
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,False,Pass
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,False,Pass

In [4]:
student_info['imd_band'] = student_info['imd_band'].replace('10-20', '10-20%')

In [5]:
student_info['imd_band'] = student_info['imd_band'].replace('?', 'Unknown')

In [6]:
student_info['disability'] = student_info['disability'].map({'Y':True, 'N':False})

In [21]:
student_info.info()

<class 'pandas.DataFrame'>
RangeIndex: 32593 entries, 0 to 32592
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   code_module           32593 non-null  str
 1   code_presentation     32593 non-null  str
 2   id_student            32593 non-null  int64
 3   gender                32593 non-null  str
 4   region                32593 non-null  str
 5   highest_education     32593 non-null  str
 6   imd_band              32593 non-null  str
 7   age_band              32593 non-null  str
 8   num_of_prev_attempts  32593 non-null  int64
 9   studied_credits       32593 non-null  int64
 10  disability            32593 non-null  bool
 11  final_result          32593 non-null  str
dtypes: bool(1), int64(3), str(8)
memory usage: 2.8 MB

In [ ]:
student_assess = pd.read_csv('raw_data/studentAssessment.csv')

In [22]:
student_assess.head()

   id_assessment  id_student  date_submitted  is_banked  score
0           1752       11391              18      False   78.0
1           1752       28400              22      False   70.0
2           1752       31604              17      False   72.0
3           1752       32885              26      False   69.0
4           1752       38053              19      False   79.0

In [10]:
student_assess['score'] = pd.to_numeric(student_assess['score'], errors='coerce')

In [11]:
student_assess['is_banked'] = student_assess['is_banked'].astype(bool)

In [12]:
student_assess.info()

<class 'pandas.DataFrame'>
RangeIndex: 173912 entries, 0 to 173911
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id_assessment   173912 non-null  int64
 1   id_student      173912 non-null  int64
 2   date_submitted  173912 non-null  int64
 3   is_banked       173912 non-null  bool
 4   score           173739 non-null  float64
dtypes: bool(1), float64(1), int64(3)
memory usage: 5.5 MB

In [ ]:
student_vle = pd.read_csv('raw_data/studentVle.csv')

In [23]:
student_vle.head()

  code_module code_presentation  id_student  site_count
0         AAA             2013J       11391         196
1         AAA             2013J       28400         430
2         AAA             2013J       30268          76
3         AAA             2013J       31604         663
4         AAA             2013J       32885         352

In [24]:
student_vle.info()

<class 'pandas.DataFrame'>
RangeIndex: 29228 entries, 0 to 29227
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   code_module        29228 non-null  str
 1   code_presentation  29228 non-null  str
 2   id_student         29228 non-null  int64
 3   site_count         29228 non-null  int64
dtypes: int64(2), str(2)
memory usage: 913.5 KB

In [16]:
# student_vle = student_vle.groupby(['code_module', 'code_presentation', 'id_student', 'id_site'])['sum_click'].sum().reset_index(name='total_clicks')
student_vle = student_vle.groupby(['code_module', 'code_presentation', 'id_student'])['id_site'].count().reset_index(name='site_count')

In [ ]:
assessments = pd.read_csv('raw_data/assessments.csv')

In [28]:
assessments.head()

  code_module code_presentation  id_assessment assessment_type  date  weight
0         AAA             2013J           1752             TMA    19    10.0
1         AAA             2013J           1753             TMA    54    20.0
2         AAA             2013J           1754             TMA   117    20.0
3         AAA             2013J           1755             TMA   166    20.0
4         AAA             2013J           1756             TMA   215    30.0

In [26]:
assessments.info()

<class 'pandas.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   code_module        206 non-null    str
 1   code_presentation  206 non-null    str
 2   id_assessment      206 non-null    int64
 3   assessment_type    206 non-null    str
 4   date               195 non-null    Int64
 5   weight             206 non-null    float64
dtypes: Int64(1), float64(1), int64(1), str(3)
memory usage: 10.0 KB

In [ ]:
assessments['date'] = pd.to_numeric(assessments['date'], errors='coerce')

In [25]:
assessments['date'] = assessments['date'].astype('Int64')

In [34]:
student_info_clean = student_info
student_info_clean.to_csv('cleaned_data/clean_studentInfo.csv', index=False)

In [35]:
student_assess_clean = student_assess
student_assess_clean.to_csv('cleaned_data/clean_studentAssessment.csv', index=False)

In [36]:
student_vle_clean = student_vle
student_vle_clean.to_csv('cleaned_data/clean_studentVle.csv', index=False)

In [37]:
assessments_clean = assessments
assessments_clean.to_csv('cleaned_data/clean_assessments.csv', index=False)