In [1]:
import pandas as pd

In [2]:
student_assessment = pd.read_csv('cleaned_data/clean_studentAssessment.csv')
assessments = pd.read_csv('cleaned_data/clean_assessments.csv')

In [3]:
assessment_scores = pd.merge(student_assessment,assessments, how='left', on='id_assessment')
assessment_scores = assessment_scores[
    [
        'code_module',
        'code_presentation',
        'id_student',
        'id_assessment',
        'assessment_type',
        'weight',
        'score'
    ]
]

In [4]:
assessment_scores.sort_values(by=['id_student', 'id_assessment'], inplace=True)

In [5]:
assessment_scores.head()

,code_module,code_presentation,id_student,id_assessment,assessment_type,weight,score
1756,AAA,2014J,6516,1758,TMA,10.0,60.0
1970,AAA,2014J,6516,1759,TMA,20.0,48.0
2376,AAA,2014J,6516,1760,TMA,20.0,63.0
2685,AAA,2014J,6516,1761,TMA,20.0,61.0
2871,AAA,2014J,6516,1762,TMA,30.0,77.0

In [6]:
assessment_scores.info()

<class 'pandas.DataFrame'>
Index: 173912 entries, 1756 to 45940
Data columns (total 7 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   code_module        173912 non-null  str
 1   code_presentation  173912 non-null  str
 2   id_student         173912 non-null  int64
 3   id_assessment      173912 non-null  int64
 4   assessment_type    173912 non-null  str
 5   weight             173912 non-null  float64
 6   score              173739 non-null  float64
dtypes: float64(2), int64(2), str(3)
memory usage: 10.6 MB

In [12]:
print(assessment_scores['score'].corr(assessment_scores['weight']))

-0.16641591424912006

In [57]:
assessment_pivot = assessment_scores.pivot_table(index='id_student', columns='assessment_type', values='score', aggfunc='mean')

In [58]:
assessment_pivot = assessment_pivot[['CMA', 'TMA', 'Exam']]

In [59]:
assessment_pivot.reset_index(inplace=True)

In [66]:
assessment_pivot.columns.name = None

In [62]:
assessment_pivot.info()

<class 'pandas.DataFrame'>
RangeIndex: 23351 entries, 0 to 23350
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_student  23351 non-null  int64
 1   CMA         14400 non-null  float64
 2   TMA         22669 non-null  float64
 3   Exam        4633 non-null   float64
dtypes: float64(3), int64(1)
memory usage: 729.8 KB

In [69]:
assessment_pivot.head()

   id_student    CMA   TMA  Exam
0        6516    NaN  61.8   NaN
1        8462    NaN  87.0   NaN
2       11391    NaN  82.0   NaN
3       23629  100.0  65.0   NaN
4       23698   75.0  72.5  80.0

In [75]:
assessment_pivot[['CMA', 'TMA', 'Exam']].describe()

                CMA           TMA         Exam
count  14400.000000  22669.000000  4633.000000
mean      79.493005     71.284393    65.117958
std       16.781101     15.347883    20.470561
min        0.000000      0.000000     0.000000
25%       72.000000     62.500000    50.000000
50%       83.000000     73.250000    66.000000
75%       91.714286     82.400000    82.000000
max      100.000000    100.000000   100.000000

In [76]:
student_info = pd.read_csv('cleaned_data/clean_studentInfo.csv')
student_vle = pd.read_csv('cleaned_data/clean_studentVle.csv')

In [98]:
assessment_pivot['id_student'].nunique()

23351

In [121]:
student_details = pd.merge(student_info, student_vle, how='left', on=['id_student', 'code_presentation', 'code_module'])
student_all_features = pd.merge(student_details, assessment_pivot, how='left', on='id_student')

In [133]:
student_all_features = student_all_features[
    [
        'id_student',
        'code_module',
        'code_presentation',
        'gender',
        'highest_education',
        'imd_band',
        'age_band',
        'disability',
        'num_of_prev_attempts',
        'studied_credits',
        'site_count',
        'CMA',
        'TMA',
        'Exam',
        'final_result'
    ]
]

In [134]:
student_all_features.info()

<class 'pandas.DataFrame'>
RangeIndex: 32593 entries, 0 to 32592
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_student            32593 non-null  int64
 1   code_module           32593 non-null  str
 2   code_presentation     32593 non-null  str
 3   gender                32593 non-null  str
 4   highest_education     32593 non-null  str
 5   imd_band              32593 non-null  str
 6   age_band              32593 non-null  str
 7   disability            32593 non-null  bool
 8   num_of_prev_attempts  32593 non-null  int64
 9   studied_credits       32593 non-null  int64
 10  site_count            29228 non-null  float64
 11  CMA                   16944 non-null  float64
 12  TMA                   25960 non-null  float64
 13  Exam                  5998 non-null   float64
 14  final_result          32593 non-null  str
dtypes: bool(1), float64(4), int64(3), str(7)
memory usage: 3.5 MB

In [135]:
student_all_features.head(10)

,id_student,code_module,code_presentation,gender,highest_education,imd_band,age_band,disability,num_of_prev_attempts,studied_credits,site_count,CMA,TMA,Exam,final_result
0,11391,AAA,2013J,M,HE Qualification,90-100%,55<=,False,0,240,196.0,NaN,82.0,NaN,Pass
1,28400,AAA,2013J,F,HE Qualification,20-30%,35-55,False,0,60,430.0,NaN,66.4,NaN,Pass
2,30268,AAA,2013J,F,A Level or Equivalent,30-40%,35-55,True,0,60,76.0,NaN,NaN,NaN,Withdrawn
3,31604,AAA,2013J,F,A Level or Equivalent,50-60%,35-55,False,0,60,663.0,NaN,76.0,NaN,Pass
4,32885,AAA,2013J,F,Lower Than A Level,50-60%,0-35,False,0,60,352.0,NaN,54.4,NaN,Pass
5,38053,AAA,2013J,M,A Level or Equivalent,80-90%,35-55,False,0,60,723.0,NaN,68.0,NaN,Pass
6,45462,AAA,2013J,M,HE Qualification,30-40%,0-35,False,0,60,355.0,NaN,68.0,NaN,Pass
7,45642,AAA,2013J,F,A Level or Equivalent,90-100%,0-35,False,0,120,531.0,NaN,72.4,NaN,Pass
8,52130,AAA,2013J,F,A Level or Equivalent,70-80%,0-35,False,0,90,593.0,NaN,71.4,NaN,Pass
9,53025,AAA,2013J,M,Post Graduate Qualification,Unknown,55<=,False,0,60,904.0,NaN,78.0,NaN,Pass

In [136]:
print(student_all_features.duplicated(subset=['id_student', 'code_module', 'code_presentation']).sum())

0

In [137]:
student_model_data = student_all_features
student_model_data.to_csv('model_data/student_data.csv', index=False)